version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8000:8000
      - 9000
    volumes:
      - /Users/maiyang/develop/docker_workspace/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://192.168.0.56:9000
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://192.168.0.56:3000
      - DRONE_SECRET=hello1234
      - HTTP_PROXY=http://192.168.0.56:1087
      - HTTPS_PROXY=http://192.168.0.56:1087

  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=hello1234
