global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - localhost:9090
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - 172.18.0.6:9121
