mysql:
    image: mysql:5.7.20
    container_name: mysql5.7.20
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
        - /Users/maiyang/develop/docker_workspace/mysql/data/:/var/lib/mysql
        - /Users/maiyang/develop/docker_workspace/mysql/logs:/logs
