apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-08-01T11:59:41Z
  generateName: hello-go-659f58bcd4-
  labels:
    pod-template-hash: "2159146780"
    run: hello-go
  name: hello-go-659f58bcd4-z52hk
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-go-659f58bcd4
    uid: 5f3e09ff-9582-11e8-b90a-c217d7775f38
  resourceVersion: "1532"
  selfLink: /api/v1/namespaces/default/pods/hello-go-659f58bcd4-z52hk
  uid: 5f3f4707-9582-11e8-b90a-c217d7775f38
spec:
  containers:
  - image: hello-go:v2
    imagePullPolicy: Never
    name: hello-go
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4v4hg
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-4v4hg
    secret:
      defaultMode: 420
      secretName: default-token-4v4hg
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T11:59:41Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T11:59:42Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T11:59:41Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://700ed922cc577edb7f812124b8fdb2c268fc9b14ee14b0df6baa0131d4425d22
    image: hello-go:v2
    imageID: docker://sha256:9729cb4edf53577fe08c2f246d3ba5b7b6f6dba0c9c5f586a42069168d706a56
    lastState: {}
    name: hello-go
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-08-01T11:59:41Z
  hostIP: 192.168.64.4
  phase: Running
  podIP: 172.17.0.7
  qosClass: BestEffort
  startTime: 2018-08-01T11:59:41Z
