web:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        - "xpack.security.enabled=false"
